In [1]:
from collections import Counter, deque

In [2]:
import numpy as np
import pandas as pd
import heapq


In [100]:
f = open("day11.txt",'r')
data = f.read().split("\n")


In [215]:
data = '''5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526'''.split("\n")


data = np.array([[int(d) for d in row] for row in data])

In [216]:
steps = []
count = 0
for i in range(5):
    steps.append(data.copy())
    print(i)
    print(data)
    data+=1
    flashed = []
    while (data == 10).sum()>0:
        data_copy = data.copy()
        for i in range(len(data)):
            for j in range(len(data)):
                if data[i,j] >9:
                    x_min = max(i-1,0)
                    x_max = min(i+1,len(data))
                    y_min = max(j-1,0)
                    y_max = min(j+1,len(data))
                    data_copy[x_min:x_max+1, y_min:y_max+1] += 1
                    flashed.append([i,j])
                    data_copy[i,j]=0
        for f in flashed:
            data_copy[f[0],f[1]]=0
        data = data_copy.copy()
        
                    
        
    count+=(data>9).sum()
    data[data>9] = 0
#     print(data)
#     print()
    if data.sum() == 0:
        print(i)
        break
count

0
[[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]
1
[[6 5 9 4 2 5 4 3 3 4]
 [3 8 5 6 9 6 5 8 2 2]
 [6 3 7 5 6 6 7 2 8 4]
 [7 2 5 2 4 4 7 2 5 7]
 [7 4 6 8 4 9 6 5 8 9]
 [5 2 7 8 6 3 5 7 5 6]
 [3 2 8 7 9 5 2 8 3 2]
 [7 9 9 3 9 9 2 2 4 5]
 [5 9 5 7 9 5 9 6 6 5]
 [6 3 9 4 8 6 2 6 3 7]]
2
[[8 8 0 7 4 7 6 5 5 5]
 [5 0 8 9 0 8 7 0 5 4]
 [8 5 9 7 8 8 9 6 0 8]
 [8 4 8 5 7 6 9 6 0 0]
 [8 7 0 0 9 0 8 8 0 0]
 [6 6 0 0 0 8 8 9 8 9]
 [6 8 0 0 0 0 5 9 4 3]
 [0 0 0 0 0 0 7 4 5 6]
 [9 0 0 0 0 0 0 8 7 6]
 [8 7 0 0 0 0 6 8 4 8]]
3
[[0 0 5 0 9 0 0 8 6 6]
 [8 5 0 0 8 0 0 5 7 5]
 [9 9 0 0 0 0 0 0 3 9]
 [9 7 0 0 0 0 0 0 4 1]
 [9 9 3 5 0 8 0 0 6 3]
 [7 7 1 2 3 0 0 0 0 0]
 [7 9 1 1 2 5 0 0 0 9]
 [2 2 1 1 1 3 0 0 0 0]
 [0 4 2 1 1 2 5 0 0 0]
 [0 0 2 1 1 1 9 0 0 0]]
4
[[2 2 6 3 0 3 1 9 7 7]
 [0 9 2 3 0 3 1 6 9 7]
 [0 0 3 2 2 2 1 1 5 

1

In [217]:
data

array([[4, 4, 8, 4, 1, 4, 4, 0, 0, 0],
       [2, 0, 4, 4, 1, 4, 4, 0, 0, 0],
       [2, 2, 5, 3, 3, 3, 3, 4, 9, 3],
       [1, 1, 5, 2, 3, 3, 3, 2, 7, 4],
       [1, 1, 8, 7, 3, 0, 3, 2, 8, 5],
       [1, 1, 6, 4, 6, 3, 3, 2, 3, 3],
       [1, 1, 5, 3, 4, 7, 2, 2, 3, 1],
       [5, 5, 4, 3, 3, 5, 2, 2, 3, 3],
       [2, 6, 4, 3, 3, 5, 8, 3, 2, 2],
       [2, 2, 4, 3, 3, 4, 1, 3, 2, 2]])

In [236]:
temp = '''0050900866
8500800575
9900000039
9700000041
9935080063
7712300000
7911250009
2211130000
0421125000
0021119000'''.split("\n")


temp = np.array([[int(d) for d in row] for row in temp])

In [237]:
np.all(temp == steps[3])

True

In [235]:
steps[1]

array([[6, 5, 9, 4, 2, 5, 4, 3, 3, 4],
       [3, 8, 5, 6, 9, 6, 5, 8, 2, 2],
       [6, 3, 7, 5, 6, 6, 7, 2, 8, 4],
       [7, 2, 5, 2, 4, 4, 7, 2, 5, 7],
       [7, 4, 6, 8, 4, 9, 6, 5, 8, 9],
       [5, 2, 7, 8, 6, 3, 5, 7, 5, 6],
       [3, 2, 8, 7, 9, 5, 2, 8, 3, 2],
       [7, 9, 9, 3, 9, 9, 2, 2, 4, 5],
       [5, 9, 5, 7, 9, 5, 9, 6, 6, 5],
       [6, 3, 9, 4, 8, 6, 2, 6, 3, 7]])

In [221]:
temp

array([[4, 4, 8, 4, 1, 4, 4, 0, 0, 0],
       [2, 0, 4, 4, 1, 4, 4, 0, 0, 0],
       [2, 2, 5, 3, 3, 3, 3, 4, 9, 3],
       [1, 1, 5, 2, 3, 3, 3, 2, 7, 4],
       [1, 1, 8, 7, 3, 0, 3, 2, 8, 5],
       [1, 1, 6, 4, 6, 3, 3, 2, 3, 3],
       [1, 1, 5, 3, 4, 7, 2, 2, 3, 1],
       [5, 5, 4, 3, 3, 5, 2, 2, 3, 3],
       [2, 6, 4, 3, 3, 5, 8, 3, 2, 2],
       [2, 2, 4, 3, 3, 4, 1, 3, 2, 2]])